Update README.md to recommend installing BLAST from FTP (#3)
Since we had the following error reported:



    (base) /data/CommonMechanism-main/src$ ./run_pipeline.sh -q /data/Inputs/input.fasta -o /data/Outputs/ -d /data -t 8 -b
     >> STEP 0: Checking for valid options...
     >> STARTED AT Thu Apr 11 23:48:32 UTC 2024
     >> Screening /data/Inputs/input.fasta
     >> STEP 1: Checking for biorisk genes...
            ...running transeq
            ...running hmmscan
            ...checking hmmscan results
                     --> Biorisks: no hits detected, PASS
        STEP 1 completed at Thu Apr 11 23:48:32 UTC 2024

     >> STEP 2: Checking regulated pathogen proteins...
            ...running run_blastx.sh
            ...checking for valid options...
            ...running protein search...
    BLAST Database error: Error: Not a valid version 4 database.
            ...checking blast results
            ERROR: Homology search has failed
        STEP 2 completed at Thu Apr 11 23:48:33 UTC 2024

     >> STEP 3: Checking regulated pathogen nucleotides...
            ...fetching noncoding regions
    Traceback (most recent call last):
      File "/data/CommonMechanism-main/src/./fetch_nc_bits.py", line 9, in <module>
        from Bio import SeqIO
    ModuleNotFoundError: No module named 'Bio'
            ...skipping nucleotide search
        STEP 3 completed at Thu Apr 11 23:48:34 UTC 2024

     >> STEP 4: Checking any pathogen regions for benign components...
    BLAST Database error: Error: Not a valid version 4 database.
            ...no regulated regions to clear
     >> COMPLETED AT Thu Apr 11 23:48:34 UTC 2024
    rm: cannot remove '/data/Outputs/*.tmp': No such file or directory