Bugfix: filter out deleted and invalid taxonomy ids (#18)
## Background

We were sometimes seeing this kind of error:
```
 >> STEP 2: Checking regulated pathogen proteins...
Problem with taxID 2855502 - check that your taxID and protein database are up to date
Traceback (most recent call last):
  File "/home/repository/commec/check_reg_path.py", line 153, in <module>
    main()
  File "/home/repository/commec/check_reg_path.py", line 57, in main
    blast = taxdist(blast, reg_ids, vax_ids, args.db + "/taxonomy/", args.threads)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/repository/commec/utils.py", line 118, in taxdist
    zip(
TypeError: 'float' object is not iterable
	 ERROR: command 'python /home/repository/commec/check_reg_path.py -i ./output/test.nr.blastx -d /home/cm-dbs/ -t 8' failed
```

after investigation, this turned out to be because `pytaxonkit.lineage` will return a column full of mostly `NaN`s if the taxonomy id has been deleted or cannot be found. Now we log a warning about that and drop the hits with outdated taxids.

## Changes

### Bug fixes
* Filter out deleted and invalid taxonomy ids
* Remove check for `pytaxonkit.lineage` results introduced in refactor (same issue caught by the filter above)

### Refactoring
* Add tests for some of the `blast_tools.py` methods
* Removed unused method in `blast_tools.py` and gave a few others more descriptive names