Split check_blastfile utility into two functions (#1)
We ran into an issue in testing due to not running a check about whether a file exists. My hope is that making the check_blastfile utility more explicit, we'll be able to avoid this kind of error in future.
 
```
 >> STEP 4: Checking any pathogen regions for benign components...
Traceback (most recent call last):
  File "nti/CommonMechanism/src/check_benign.py", line 177, in <module>
        ...no housekeeping protein hits
    main()
  File "nti/CommonMechanism/src/check_benign.py", line 172, in main
    check_for_benign(args.sample_name, coords, benign_desc)
  File "nti/CommonMechanism/src/check_benign.py", line 74, in check_for_benign
    cmscan = readcmscan(cmscan)
             ^^^^^^^^^^^^^^^^^^
  File "nti/CommonMechanism/src/utils.py", line 262, in readcmscan
    with open(fileh, 'r') as f:
         ^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'A22393.1_200_573_772_rs.fa.benign.cmscan'
 >> COMPLETED AT Sun Mar  3 18:10:39 EST 2024
```